made cc logo as link instead of whole header by updating header.html ,style.css
creativecommons/cc-resource-archive pull request #145
Opened 2023-04-01 09:16 UTC by RishabhRajJoshi

## Fixes

Fixes #70 by @RishabhRajJoshi 

## Description
whole header div was enclosed inside the anchor tag, due to which the whole header acted as a link after changes only logo act 
as a link

## Technical details
1) first, removed logo from style.css and added an img tag to the header.html
2) added an anchor tag across the image
3) instead of redirecting it to [creativecommon.org](https://creativecommons.org/), now it redirects to the home page of resource archive website 

## Screenshots
![image](https://user-images.githubusercontent.com/112555922/229277132-c2ffa9dc-5b83-42bb-ac25-27d7c1e54d00.png)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-04-06 05:58 UTC, justaskulkarni requested changes
@RishabhRajJoshi good work. However, you have missed one case, have a look.
This is the current look of the submit a resource page:
![image](https://user-images.githubusercontent.com/98650743/230282526-96884a7b-50ad-4120-ad10-24d65a4deca2.png)
This is how the submit a resource page looks like after your PR
![image](https://user-images.githubusercontent.com/98650743/230282612-ecddc5c2-8ef5-4f91-b7a4-5fec56f8fbc4.png)
As you can see the logos do not appear
This is a screenshot of `docs/submission.html` file:
![image](https://user-images.githubusercontent.com/98650743/230282782-724af333-8560-44b9-ab90-d4b0d3ce10ac.png)
The reason for that is simple: removal of background image property from the banner cc id selector. 
In order to fix this we must make the following changes in `docs/submission.html`:
![image](https://user-images.githubusercontent.com/98650743/230283034-9ede285e-a39d-497a-bd69-d1c91329a3b3.png)
I have tested this locally and can confirm that it works

2023-04-06 06:49 UTC, justaskulkarni commented
Update:
You will also need to add
`<script>
  const globalHeader = document.getElementById("global-header");
  const handleExplore = (event) => {
    globalHeader.classList.toggle("active");
    event.preventDefault();
  }
</script>`
after `</body>` in `docs/submission.html` so that the expanding menu works.

2023-04-06 14:09 UTC, RishabhRajJoshi commented
@justaskulkarni  Thanks for rectifying the error. I have updated the pull request.

2023-04-07 13:22 UTC, justaskulkarni requested changes
The indentation in `docs/_includes/header.html` hasn't been fixed yet
![image](https://user-images.githubusercontent.com/98650743/230615279-eb3bcb44-7cca-4ccb-90da-f6576c3fd41d.png)
There are blank lines present in the code between the closing </script> tag and the closing </html> tag. It would be ideal to remove them for improved code cleanliness.
![image](https://user-images.githubusercontent.com/98650743/230616138-21df3485-219f-4055-a3f7-1e33ba2604c9.png)

2023-04-08 07:48 UTC, justaskulkarni approved these changes
Looks good to me. Good work @RishabhRajJoshi

2024-04-05 20:20 UTC, merged