Added image-alt fields for all resources and resourcetemplate
creativecommons/cc-resource-archive pull request #332
Opened 2024-10-09 15:01 UTC by Queen-codes

## Fixes

- Fixes #307 by @Murdock9803 

## Description
This pull request expands on #328 and adds `image-alt` field to all resource files present in the `resources` folder.  Also, there is an `image-alt` field in `resourcetemplate.md`  and a description of the `image-alt` field to help users understand what they need to add in that field.

## Tests
I tested the code locally by inspecting the image element of each resource in the browser to ensure the alt attribute is loading correctly.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2024-10-11 17:03 UTC, Queen-codes commented
hi @possumbilities . I hope you're doing well. I just wanted to follow up on this PR. i understand you have a busy schedule and a lot of contributions to attend to. I'll appreciate your input and feedback when you can. Thank you.

2024-10-11 20:25 UTC, Queen-codes commented
Hello @possumbilities, I’ve resolved the conflicts arising from the recent merge. However, I’m not sure I handled it in the best way possible. Please let me know your thoughts and if any adjustments are needed. Thank you

2024-10-12 03:55 UTC, Murdock9803 commented on docs/_resources/big-buck-bunny-loves-creative-commons.md
> +image-alt: "An open book with the a rabbit's picture on the left page and creative coomon's logo on the right"
There is typing mistake in `Creative Commons` in this line

2024-10-12 03:56 UTC, Murdock9803 commented on docs/_resources/cash-music-creative-commons-portal.md
> +image-alt: "A poster explaining CC's misssion in offering free legal tools for creators to share their work"
mission - spelling is wrong

2024-10-12 03:58 UTC, Murdock9803 commented on docs/_resources/learn-creative-commons-in-3-minutes.md
> +image-alt: "An infograhic explaining how the Creative Common licences work in arabic language"
spellings for `infographic` and `commons` are not correct.

2024-10-12 04:07 UTC, Murdock9803 requested changes

2024-10-12 04:07 UTC, Murdock9803 commented on docs/_resources/open-content-licensing-for-educators.md
> +image-alt: "A infographic outlining the structure of an OERu website"
"An" infographic.

2024-10-12 04:07 UTC, Murdock9803 commented on docs/_resources/open-policy-network.md
> +image-alt: "A picture of the Open Policy Network webiste's homepage"
website spelling is wrong.

2024-10-12 04:07 UTC, Murdock9803 commented on docs/_resources/why-open-education-matters.md
> +image-alt: "A cartoon illustration of a child studying, with a rocket and scientific equations representing asprirations."
aspirations - spelling error

2024-10-12 04:07 UTC, Murdock9803 commented on resourcetemplate.md
> +Image-full should be 500px * 375px. Image-thumb should be 200*150. Put in the "docs/\_assets/images" folder. Use the full title as the filename, separated by hyphens.
In this line, there is an extra `\` in `"docs/\_assets/images"`.

2024-10-12 04:07 UTC, Murdock9803 commented on resourcetemplate.md
> +Image-alt is a brief and descriptive text that explains the content of the image for those who can not see it. Image-alt should be concise and brief and depicit the purpose of the image.
depict - spelling mistake there

2024-10-12 04:07 UTC, Murdock9803 commented on resourcetemplate.md
> +_Last updated April 25, 2014_
Why to change the punctuation ? Just asking the reason behind it :raised_hands:

2024-10-12 04:09 UTC, Murdock9803 commented
@Queen-codes I have left some review comments, Please resolve them. Also, are all the resources covered under this Pull Request ?

2024-10-13 08:02 UTC, Queen-codes commented on resourcetemplate.md
> +_Last updated April 25, 2014_
honest mistake. reverting now

2024-10-13 08:26 UTC, Queen-codes commented
> @Queen-codes I have left some review comments, Please resolve them. Also, are all the resources covered under this Pull Request ?

Hi @Murdock9803  Thanks for the review. I have effected all the necessary corrections and checked to see if any resource file is missing. Everything is updated now and also in the `md` format per the last pull request merged into the codebase.

2024-10-14 00:26 UTC, Murdock9803 commented on resourcetemplate.md
> +Last updated April 25, 2014
@Queen-codes I meant we should not change this line, Earlier it had asterisks (`*`) and they were changed to be underscores (`_`) by you. I think we should keep the changes minimum so please make this text enclosed in asterisks as before 🙌

2024-10-14 00:33 UTC, Murdock9803 commented on docs/_layouts/listing.html
> +              <img class="thumbnail" src="{{page.image-thumb}}" alt="{% if
In the `alt` attribute, there are nested quotation marks ( `"   " "   "`). This way it becomes difficult for someone to understand it. These can be changed to ( `"    ' '     "` ). I mean we can use `single quotation marks` enclosed inside `double quotation marks`.

2024-10-14 00:35 UTC, Murdock9803 commented
@Queen-codes Thanks for the changes you've done so far, I left some final review comments, please do the changes 🙌

2024-10-14 06:05 UTC, Queen-codes commented on resourcetemplate.md
> +Last updated April 25, 2014
Hi, changed, but i do have a question. Since there has been an addition to the file-the addition of the image-alt field and the description, shouldn't the date be chnaged too? To reflect the addition and update of the template
```suggestion
*Last updated April 25, 2014*
```

2024-10-17 17:09 UTC, Queen-codes commented
hi @possumbilities . I think I've made all the changes to this PR. Let me know if you have any more changes when you have a minute. Thank you.

2024-10-24 19:26 UTC, possumbilities approved these changes
@Queen-codes this is a lot of really good work! Thank you for this. Approved.

2024-10-24 19:29 UTC, possumbilities commented
@Queen-codes It appears, on second glance there are still a few spelling errors outlined by @Murdock9803 

Can you go through and correct those spelling errors and then I'll move forward with a merger?

2024-10-24 19:37 UTC, Queen-codes commented
> @Queen-codes It appears, on second glance there are still a few spelling errors outlined by @Murdock9803
> 
> Can you go through and correct those spelling errors and then I'll move forward with a merger?

okay, on it

2024-10-24 20:01 UTC, Queen-codes commented
hi @possumbilities . I have gone through each file thoroughly and fixed the spelling errors. I have also double checked to ensure I wasn't missing anything from what @Murdock9803 pointed out. Additionally, I capitalized all Creative Commons that appeared.

2024-10-24 20:12 UTC, possumbilities commented on resourcetemplate.md
> +Image-full should be 500px * 375px. Image-thumb should be 200*150. Put in the "docs/\_assets/images" folder. Use the full title as the filename, separated by hyphens.
@Queen-codes this still needs correction

2024-10-24 20:15 UTC, possumbilities approved these changes

2024-10-24 20:16 UTC, merged

2024-10-24 20:17 UTC, possumbilities commented
@Queen-codes if you comment on the original issue I can assign you!